// Generated by gencpp from file openrtk_msg/openrtk_gnss.msg
// DO NOT EDIT!


#ifndef OPENRTK_MSG_MESSAGE_OPENRTK_GNSS_H
#define OPENRTK_MSG_MESSAGE_OPENRTK_GNSS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace openrtk_msg
{
template <class ContainerAllocator>
struct openrtk_gnss_
{
  typedef openrtk_gnss_<ContainerAllocator> Type;

  openrtk_gnss_()
    : header()
    , gps_week(0)
    , gps_millisecs(0)
    , position_type(0)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , latitude_std_deviation(0.0)
    , longitude_std_deviation(0.0)
    , height_std_deviation(0.0)
    , num_of_satellites(0)
    , num_satellite_in_solution(0)
    , hdop(0.0)
    , diffage(0.0)
    , north_vel(0.0)
    , east_vel(0.0)
    , up_vel(0.0)
    , north_vel_std_deviation(0.0)
    , east_vel_std_deviation(0.0)
    , up_vel_std_deviation(0.0)  {
    }
  openrtk_gnss_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gps_week(0)
    , gps_millisecs(0)
    , position_type(0)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , latitude_std_deviation(0.0)
    , longitude_std_deviation(0.0)
    , height_std_deviation(0.0)
    , num_of_satellites(0)
    , num_satellite_in_solution(0)
    , hdop(0.0)
    , diffage(0.0)
    , north_vel(0.0)
    , east_vel(0.0)
    , up_vel(0.0)
    , north_vel_std_deviation(0.0)
    , east_vel_std_deviation(0.0)
    , up_vel_std_deviation(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _gps_week_type;
  _gps_week_type gps_week;

   typedef uint32_t _gps_millisecs_type;
  _gps_millisecs_type gps_millisecs;

   typedef uint8_t _position_type_type;
  _position_type_type position_type;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _height_type;
  _height_type height;

   typedef float _latitude_std_deviation_type;
  _latitude_std_deviation_type latitude_std_deviation;

   typedef float _longitude_std_deviation_type;
  _longitude_std_deviation_type longitude_std_deviation;

   typedef float _height_std_deviation_type;
  _height_std_deviation_type height_std_deviation;

   typedef uint8_t _num_of_satellites_type;
  _num_of_satellites_type num_of_satellites;

   typedef uint8_t _num_satellite_in_solution_type;
  _num_satellite_in_solution_type num_satellite_in_solution;

   typedef float _hdop_type;
  _hdop_type hdop;

   typedef float _diffage_type;
  _diffage_type diffage;

   typedef float _north_vel_type;
  _north_vel_type north_vel;

   typedef float _east_vel_type;
  _east_vel_type east_vel;

   typedef float _up_vel_type;
  _up_vel_type up_vel;

   typedef float _north_vel_std_deviation_type;
  _north_vel_std_deviation_type north_vel_std_deviation;

   typedef float _east_vel_std_deviation_type;
  _east_vel_std_deviation_type east_vel_std_deviation;

   typedef float _up_vel_std_deviation_type;
  _up_vel_std_deviation_type up_vel_std_deviation;





  typedef boost::shared_ptr< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> const> ConstPtr;

}; // struct openrtk_gnss_

typedef ::openrtk_msg::openrtk_gnss_<std::allocator<void> > openrtk_gnss;

typedef boost::shared_ptr< ::openrtk_msg::openrtk_gnss > openrtk_gnssPtr;
typedef boost::shared_ptr< ::openrtk_msg::openrtk_gnss const> openrtk_gnssConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openrtk_msg::openrtk_gnss_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openrtk_msg::openrtk_gnss_<ContainerAllocator1> & lhs, const ::openrtk_msg::openrtk_gnss_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gps_week == rhs.gps_week &&
    lhs.gps_millisecs == rhs.gps_millisecs &&
    lhs.position_type == rhs.position_type &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.height == rhs.height &&
    lhs.latitude_std_deviation == rhs.latitude_std_deviation &&
    lhs.longitude_std_deviation == rhs.longitude_std_deviation &&
    lhs.height_std_deviation == rhs.height_std_deviation &&
    lhs.num_of_satellites == rhs.num_of_satellites &&
    lhs.num_satellite_in_solution == rhs.num_satellite_in_solution &&
    lhs.hdop == rhs.hdop &&
    lhs.diffage == rhs.diffage &&
    lhs.north_vel == rhs.north_vel &&
    lhs.east_vel == rhs.east_vel &&
    lhs.up_vel == rhs.up_vel &&
    lhs.north_vel_std_deviation == rhs.north_vel_std_deviation &&
    lhs.east_vel_std_deviation == rhs.east_vel_std_deviation &&
    lhs.up_vel_std_deviation == rhs.up_vel_std_deviation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openrtk_msg::openrtk_gnss_<ContainerAllocator1> & lhs, const ::openrtk_msg::openrtk_gnss_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openrtk_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96b04d76b1ddd2c5be37a77c869d504d";
  }

  static const char* value(const ::openrtk_msg::openrtk_gnss_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96b04d76b1ddd2c5ULL;
  static const uint64_t static_value2 = 0xbe37a77c869d504dULL;
};

template<class ContainerAllocator>
struct DataType< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openrtk_msg/openrtk_gnss";
  }

  static const char* value(const ::openrtk_msg::openrtk_gnss_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint16 gps_week\n"
"uint32 gps_millisecs\n"
"uint8 position_type\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 height\n"
"float32 latitude_std_deviation\n"
"float32 longitude_std_deviation\n"
"float32 height_std_deviation\n"
"uint8 num_of_satellites\n"
"uint8 num_satellite_in_solution\n"
"float32 hdop\n"
"float32 diffage\n"
"float32 north_vel\n"
"float32 east_vel\n"
"float32 up_vel\n"
"float32 north_vel_std_deviation\n"
"float32 east_vel_std_deviation\n"
"float32 up_vel_std_deviation\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::openrtk_msg::openrtk_gnss_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gps_week);
      stream.next(m.gps_millisecs);
      stream.next(m.position_type);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.height);
      stream.next(m.latitude_std_deviation);
      stream.next(m.longitude_std_deviation);
      stream.next(m.height_std_deviation);
      stream.next(m.num_of_satellites);
      stream.next(m.num_satellite_in_solution);
      stream.next(m.hdop);
      stream.next(m.diffage);
      stream.next(m.north_vel);
      stream.next(m.east_vel);
      stream.next(m.up_vel);
      stream.next(m.north_vel_std_deviation);
      stream.next(m.east_vel_std_deviation);
      stream.next(m.up_vel_std_deviation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct openrtk_gnss_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openrtk_msg::openrtk_gnss_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openrtk_msg::openrtk_gnss_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gps_week: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.gps_week);
    s << indent << "gps_millisecs: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.gps_millisecs);
    s << indent << "position_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_type);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "latitude_std_deviation: ";
    Printer<float>::stream(s, indent + "  ", v.latitude_std_deviation);
    s << indent << "longitude_std_deviation: ";
    Printer<float>::stream(s, indent + "  ", v.longitude_std_deviation);
    s << indent << "height_std_deviation: ";
    Printer<float>::stream(s, indent + "  ", v.height_std_deviation);
    s << indent << "num_of_satellites: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_of_satellites);
    s << indent << "num_satellite_in_solution: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_satellite_in_solution);
    s << indent << "hdop: ";
    Printer<float>::stream(s, indent + "  ", v.hdop);
    s << indent << "diffage: ";
    Printer<float>::stream(s, indent + "  ", v.diffage);
    s << indent << "north_vel: ";
    Printer<float>::stream(s, indent + "  ", v.north_vel);
    s << indent << "east_vel: ";
    Printer<float>::stream(s, indent + "  ", v.east_vel);
    s << indent << "up_vel: ";
    Printer<float>::stream(s, indent + "  ", v.up_vel);
    s << indent << "north_vel_std_deviation: ";
    Printer<float>::stream(s, indent + "  ", v.north_vel_std_deviation);
    s << indent << "east_vel_std_deviation: ";
    Printer<float>::stream(s, indent + "  ", v.east_vel_std_deviation);
    s << indent << "up_vel_std_deviation: ";
    Printer<float>::stream(s, indent + "  ", v.up_vel_std_deviation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENRTK_MSG_MESSAGE_OPENRTK_GNSS_H
