# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from openrtk_msg/openrtk_imu.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class openrtk_imu(genpy.Message):
  _md5sum = "d40ff5f1b47965532ea9f61ecd997abb"
  _type = "openrtk_msg/openrtk_imu"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
uint16 gps_week
uint32 gps_millisecs
float32 x_acceleration
float32 y_acceleration
float32 z_acceleration
float32 x_gyro_rate
float32 y_gyro_rate
float32 z_gyro_rate

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','gps_week','gps_millisecs','x_acceleration','y_acceleration','z_acceleration','x_gyro_rate','y_gyro_rate','z_gyro_rate']
  _slot_types = ['std_msgs/Header','uint16','uint32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,gps_week,gps_millisecs,x_acceleration,y_acceleration,z_acceleration,x_gyro_rate,y_gyro_rate,z_gyro_rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(openrtk_imu, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gps_week is None:
        self.gps_week = 0
      if self.gps_millisecs is None:
        self.gps_millisecs = 0
      if self.x_acceleration is None:
        self.x_acceleration = 0.
      if self.y_acceleration is None:
        self.y_acceleration = 0.
      if self.z_acceleration is None:
        self.z_acceleration = 0.
      if self.x_gyro_rate is None:
        self.x_gyro_rate = 0.
      if self.y_gyro_rate is None:
        self.y_gyro_rate = 0.
      if self.z_gyro_rate is None:
        self.z_gyro_rate = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.gps_week = 0
      self.gps_millisecs = 0
      self.x_acceleration = 0.
      self.y_acceleration = 0.
      self.z_acceleration = 0.
      self.x_gyro_rate = 0.
      self.y_gyro_rate = 0.
      self.z_gyro_rate = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_HI6f().pack(_x.gps_week, _x.gps_millisecs, _x.x_acceleration, _x.y_acceleration, _x.z_acceleration, _x.x_gyro_rate, _x.y_gyro_rate, _x.z_gyro_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.gps_week, _x.gps_millisecs, _x.x_acceleration, _x.y_acceleration, _x.z_acceleration, _x.x_gyro_rate, _x.y_gyro_rate, _x.z_gyro_rate,) = _get_struct_HI6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_HI6f().pack(_x.gps_week, _x.gps_millisecs, _x.x_acceleration, _x.y_acceleration, _x.z_acceleration, _x.x_gyro_rate, _x.y_gyro_rate, _x.z_gyro_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.gps_week, _x.gps_millisecs, _x.x_acceleration, _x.y_acceleration, _x.z_acceleration, _x.x_gyro_rate, _x.y_gyro_rate, _x.z_gyro_rate,) = _get_struct_HI6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_HI6f = None
def _get_struct_HI6f():
    global _struct_HI6f
    if _struct_HI6f is None:
        _struct_HI6f = struct.Struct("<HI6f")
    return _struct_HI6f
