(cl:in-package openrtk_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECS-VAL
          GPS_MILLISECS
          INS_STATUS-VAL
          INS_STATUS
          INS_POSITION_TYPE-VAL
          INS_POSITION_TYPE
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          NORTH_VEL-VAL
          NORTH_VEL
          EAST_VEL-VAL
          EAST_VEL
          UP_VEL-VAL
          UP_VEL
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          HEADING-VAL
          HEADING
          LATITUDE_STD_DEVIATION-VAL
          LATITUDE_STD_DEVIATION
          LONGITUDE_STD_DEVIATION-VAL
          LONGITUDE_STD_DEVIATION
          HEIGHT_STD_DEVIATION-VAL
          HEIGHT_STD_DEVIATION
          NORTH_VEL_STD_DEVIATION-VAL
          NORTH_VEL_STD_DEVIATION
          EAST_VEL_STD_DEVIATION-VAL
          EAST_VEL_STD_DEVIATION
          UP_VEL_STD_DEVIATION-VAL
          UP_VEL_STD_DEVIATION
          ROLL_STD_DEVIATION-VAL
          ROLL_STD_DEVIATION
          PITCH_STD_DEVIATION-VAL
          PITCH_STD_DEVIATION
          HEADING_STD_DEVIATION-VAL
          HEADING_STD_DEVIATION
))