(cl:in-package openrtk_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECS-VAL
          GPS_MILLISECS
          POSITION_TYPE-VAL
          POSITION_TYPE
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          LATITUDE_STD_DEVIATION-VAL
          LATITUDE_STD_DEVIATION
          LONGITUDE_STD_DEVIATION-VAL
          LONGITUDE_STD_DEVIATION
          HEIGHT_STD_DEVIATION-VAL
          HEIGHT_STD_DEVIATION
          NUM_OF_SATELLITES-VAL
          NUM_OF_SATELLITES
          NUM_SATELLITE_IN_SOLUTION-VAL
          NUM_SATELLITE_IN_SOLUTION
          HDOP-VAL
          HDOP
          DIFFAGE-VAL
          DIFFAGE
          NORTH_VEL-VAL
          NORTH_VEL
          EAST_VEL-VAL
          EAST_VEL
          UP_VEL-VAL
          UP_VEL
          NORTH_VEL_STD_DEVIATION-VAL
          NORTH_VEL_STD_DEVIATION
          EAST_VEL_STD_DEVIATION-VAL
          EAST_VEL_STD_DEVIATION
          UP_VEL_STD_DEVIATION-VAL
          UP_VEL_STD_DEVIATION
))